-- TravelViet Supabase PostgreSQL Schema DDL
-- Execute this SQL in Supabase SQL Editor (https://supabase.com/dashboard/project/eacgavjbnhjdgnivkomo/sql/new)

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    full_name TEXT,
    phone TEXT,
    country TEXT,
    address TEXT,
    avatar TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS airlines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    logo TEXT,
    country TEXT,
    active INT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS airports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    city TEXT NOT NULL,
    country TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS flights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number TEXT NOT NULL,
    airline_id BIGINT REFERENCES airlines(id) ON DELETE CASCADE,
    origin_airport_id BIGINT REFERENCES airports(id) ON DELETE CASCADE,
    destination_airport_id BIGINT REFERENCES airports(id) ON DELETE CASCADE,
    departure_date TEXT NOT NULL,
    departure_time TEXT NOT NULL,
    arrival_time TEXT NOT NULL,
    duration_minutes INT NOT NULL,
    trip_type TEXT NOT NULL,
    stops INT DEFAULT 0,
    aircraft TEXT,
    economy_price NUMERIC NOT NULL,
    business_price NUMERIC NOT NULL,
    services TEXT,
    status TEXT DEFAULT 'available'
);

CREATE TABLE IF NOT EXISTS tours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    operator TEXT NOT NULL,
    origin TEXT NOT NULL,
    destination TEXT NOT NULL,
    country TEXT NOT NULL,
    departure_date TEXT NOT NULL,
    days INT NOT NULL,
    nights INT NOT NULL,
    airline_id BIGINT REFERENCES airlines(id) ON DELETE SET NULL,
    aircraft TEXT,
    price NUMERIC NOT NULL,
    thumbnail TEXT,
    description TEXT,
    included_services TEXT,
    excluded_services TEXT,
    status TEXT DEFAULT 'available',
    featured INT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tour_itineraries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id BIGINT REFERENCES tours(id) ON DELETE CASCADE,
    day_number INT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    meals TEXT,
    accommodation TEXT
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_code TEXT NOT NULL UNIQUE,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_phone TEXT,
    country TEXT,
    address TEXT,
    total_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'completed',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS booking_flights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
    flight_id BIGINT REFERENCES flights(id) ON DELETE CASCADE,
    fare_class TEXT NOT NULL,
    quantity INT DEFAULT 1,
    price NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_tours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
    tour_id BIGINT REFERENCES tours(id) ON DELETE CASCADE,
    quantity INT DEFAULT 1,
    price NUMERIC NOT NULL
);

-- Row Level Security (RLS) policies for open access (Anon Client Key)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE airlines ENABLE ROW LEVEL SECURITY;
ALTER TABLE airports ENABLE ROW LEVEL SECURITY;
ALTER TABLE flights ENABLE ROW LEVEL SECURITY;
ALTER TABLE tours ENABLE ROW LEVEL SECURITY;
ALTER TABLE tour_itineraries ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_flights ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_tours ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write airlines" ON airlines FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write airports" ON airports FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write flights" ON flights FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write tours" ON tours FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write tour_itineraries" ON tour_itineraries FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write bookings" ON bookings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write booking_flights" ON booking_flights FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write booking_tours" ON booking_tours FOR ALL USING (true) WITH CHECK (true);
